<a href="https://colab.research.google.com/github/helloKH/python_study/blob/master/Psypy_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Psypy 4회차 
- numpy & Pandas 실습자료
- 실습교재: Python for data analysis 2nd.
- Chapter 4 ~ 5

In [3]:
!python -V

Python 3.6.9


#### Numpy에서 제공하는 것들
- 효율적인 다차원 배열인 ndarray는 빠른 배열 계산과 유연한 **브로드캐스팅** 기능을 제공
- 반복문을 작성할 필요 없이 전체 데이터배열을 빠르게 계산할 수 있는 표준 수학함수
- 배열데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구
- 선형대수, 난수 생성기, 푸리에 변환 기능
- C, C++, 포드란으로 작성한 코드를 연결할 수 있는 C API

#### 4.1 ndarray
- N차원의 배열 객체이며, 대규모 데이터 집합을 다룰 수 있는 빠르고 유연한 자료 구조

In [0]:
import numpy as np

In [0]:
#### 임의의 값 생성
data = np.random.randn(2,3)
data

array([[-0.07779822,  2.073489  ,  0.76026552],
       [ 0.7516605 ,  1.18407855,  1.114874  ]])

In [0]:
data * 10 # 산술연산

array([[-0.7779822 , 20.73489005,  7.60265521],
       [ 7.51660498, 11.8407855 , 11.14874001]])

In [0]:
data + data

array([[-0.15559644,  4.14697801,  1.52053104],
       [ 1.503321  ,  2.3681571 ,  2.229748  ]])

- ndarray는 같은 종류의 데이터를 담을 수 있는 다차열 배열이다. ndarray의 모든 원소는 같은 자료형이어야 한다
  - shape: 각 차원의 크기를 알려주며, 튜플 형태로 제시
  - dtype: 배열에 저장된 자료형을 알려주는 객체

In [0]:
print(data.shape)

data.dtype

(2, 3)


dtype('float64')

#### 4.1.1 ndarray 생성

In [0]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [0]:
# 같은 길이를 가진 리스트는 다차월 배열 변환 가능
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
arr2.ndim

2

In [0]:
arr2.shape

(2, 4)

In [0]:
# np.array의 자료형은 추론되어 dtype에 저장됨
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [0]:
# 배열에 0 생성
np.zeros(10)
print(np.zeros((2,3,2)))

# 배열에 1 생성
np.ones(4)
np.ones((2,3,1))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [0]:
# np.arange는 range의 함수 버전
np.arange(4)

array([0, 1, 2, 3])

#### 4.1.2 ndarray의 dtype

In [6]:
# dtype는 ndarray가 메모리를 해석하기 위해 필요한 정보(메타데이터)를 담고 있음
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

arr1.dtype
arr2.dtype

dtype('int32')

In [9]:
#astype를 통해 배열의 dtype를 다른 형으로 변환
arr = np.array([1,2,3,4,5])
print(arr.dtype)

float_arr = arr.astype(np.float64)
float_arr.dtype

int64


dtype('float64')

In [10]:
#부동소수점은 아래 자리가 버려짐
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [11]:
#숫자 형식의 문자열은 숫자로 변환 가능
numberic_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
numberic_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

#### 4.13 Numpy 배열 산술 연산
- 배열은 for문을 사용하지 않고 데이터를 일괄 처리할 수 있다는 장점이 있음.
- 이를 벡터화라고 하며, 같은 크기의 배열 간 산술 연산은 각 원소 단위로 적용